#!/bin/bash
startid=1000
for u in $(pdbedit -L); do 
  #echo $u
  username=$(echo $u |awk -F ':' '{print $1}')
  userid=$(echo $u |awk -F ':' '{print $2}')
  if [ "$userid" == "4294967295" ];  then
    userid=$startid
    startid=$(expr $startid + 1)
  fi
  if [ "$(grep -c "^$username:" /etc/passwd)" == "0" ]; then 
    echo "$username:x:$userid:$userid::/:/bin/false" >> /etc/passwd
  fi
  if [ "$(grep -c "^$username:" /etc/group)" == "0" ]; then 
    echo "$username:x:$userid:" >> /etc/group
  fi
done
