name: CI


on:

  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
      - name: Run a multi-line script
        run: |
          docker build . 
      - name: list docker images
        run: |
          docker images
      - name: save docker images
        run: |
          docker save -o docker${{ steps.date.outputs.date }}.tar.gz 
      - name: Create Release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly-tag-${{ steps.date.outputs.date }}
          release_name: nightly-${{ steps.date.outputs.date }}.tar.gz
          draft: false
          prerelease: false
      - name: Upload Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: docker${{ steps.date.outputs.date }}.tar.gz
          asset_name: docker${{ steps.date.outputs.date }}.tar.gz
          asset_content_type: application/octet-stream
